services:
  - type: web
    name: my-python-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    pythonVersion: "3.13.1"  # Specify your desired Python version
